### ISSUE TITLE
inline fragments

### ISSUE THREAD

**Issue by tessi** [tessi/ecto_fragment_extras#2]
@bamorim do you mind if I add your version of fragments with inline params

```elixir
fragment("foo(#{user.name}, #{^bar})")
```

to this library? maybe with the name `inline_fragment` (can't come up with something better or shorter, shadowing ectos `fragment` is not possible I tried that already :D)

**Comment by bamorim** [comment]
I added already. Wasn't it pushed?

**Comment by bamorim** [comment]
Ah, nevermind, I thought this was on ecto repo. Sure. Go ahead. :)
